# LIBRETA DE TRABAJO

## 1. Crear entorno virtual
'python3 -m venv .venv
source .venv/bin/activate'

## 2. Importar librerias Python
'pip install -r requirements.txt'

## 3. Generar un Data frame desde la base de datos.csv

In [2]:
import pandas as pd
df = pd.read_csv ("penguins_raw.csv")
df

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007-11-11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007-11-11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007-11-16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007-11-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007-11-16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N98A2,Yes,2009-11-19,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A1,No,2009-11-21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A2,No,2009-11-21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A1,Yes,2009-11-21,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A2,Yes,2009-11-21,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN

## 4 Consultas básicas, número de individuos, especies y distribucion en las islas

In [ ]:
# Contar cuantas especies se han detectado
conteo_de_espeies = df.groupby('Species').size().reset_index(name='Count')
print("Las especies detectadas son: ")
print(conteo_de_espeies, "\n")
df


# Contar cuantas especies se han detectado por isla
avistamientos_por_isla = df.groupby(['Species', 'Island']).size().reset_index(name='Count')
print("Los avistamientos de especies por isla son: ")
print(avistamientos_por_isla, "\n")

df['Island'].value_counts()

# Contar en cuántas islas aparece cada individuo
islands_por_individuo = df.groupby('Individual ID')['Island'].nunique()

# Filtrar los que aparecen en más de una isla
duplicados = islands_por_individuo[islands_por_individuo > 1]

if not duplicados.empty:
    print("Individual IDs presentes en múltiples islas:")
else:
    print("No hay Individual IDs en más de una isla.")

detalle = df.groupby('Individual ID')['Island'].unique()

duplicados_detalle = detalle[detalle.apply(len) > 1]

print(duplicados_detalle)

Las especies detectadas son:
                                     Species  Count
0        Adelie Penguin (Pygoscelis adeliae)    152
1  Chinstrap penguin (Pygoscelis antarctica)     68
2          Gentoo penguin (Pygoscelis papua)    124

Los avistamientos de especies por isla son:
                                     Species     Island  Count
0        Adelie Penguin (Pygoscelis adeliae)     Biscoe     44
1        Adelie Penguin (Pygoscelis adeliae)      Dream     56
2        Adelie Penguin (Pygoscelis adeliae)  Torgersen     52
3  Chinstrap penguin (Pygoscelis antarctica)      Dream     68
4          Gentoo penguin (Pygoscelis papua)     Biscoe    124

Individual IDs presentes en múltiples islas:
Individual ID
N1A1     [Torgersen, Biscoe]
N1A2     [Torgersen, Biscoe]
N21A1        [Dream, Biscoe]
N21A2        [Dream, Biscoe]
N22A1        [Dream, Biscoe]
                ...
N73A2     [Torgersen, Dream]
N7A1     [Torgersen, Biscoe]
N7A2     [Torgersen, Biscoe]
N8A1     [Torgersen, Biscoe]
N8A2     [Torgersen, Biscoe]
Name: Island, Length: 78, dtype: object

## 5 Correción de formato de fecha

In [4]:
def parse_fecha(x):
    for fmt in ('%Y-%m-%d', '%d/%m/%Y', '%m/%d/%Y', '%Y/%m/%d'):
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            continue
    return pd.NaT  # si ninguno funciona

df['Date Egg'] = df['Date Egg'].apply(parse_fecha)

# Ahora sí formateas
df['Date Egg'] = df['Date Egg'].dt.strftime('%Y/%m/%d')
df

,studyName,Sample Number,Species,Region,Island,Stage,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A1,Yes,2007/11/11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N1A2,Yes,2007/11/11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A1,Yes,2007/11/16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N2A2,Yes,2007/11/16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Anvers,Torgersen,"Adult, 1 Egg Stage",N3A1,Yes,2007/11/16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N98A2,Yes,2009/11/19,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A1,No,2009/11/21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N99A2,No,2009/11/21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A1,Yes,2009/11/21,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Anvers,Dream,"Adult, 1 Egg Stage",N100A2,Yes,2009/11/21,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN


# 6 Comprobar que la columna Stage y Region siempre tienen el mismo dato y suprimirla del DF

In [5]:
#comprobar que  el dato se repite en todas las filas
for col in ['Stage', 'Region']:
    conteo = df[col].value_counts(dropna=False)
    
    print(f"\nDatos en la columna {col}:")
    print(conteo)
    
    if df[col].nunique(dropna=False) == 1:
        print(f"→ Eliminando '{col}' (solo tiene un valor)")
        df = df.drop(columns=[col])
    else:
        print(f"→ '{col}' se mantiene (tiene múltiples valores)")

df

Datos en la columna Stage:
Stage
Adult, 1 Egg Stage    344
Name: count, dtype: int64
→ Eliminando 'Stage' (solo tiene un valor)

Datos en la columna Region:
Region
Anvers    344
Name: count, dtype: int64
→ Eliminando 'Region' (solo tiene un valor)

,studyName,Sample Number,Species,Island,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie Penguin (Pygoscelis adeliae),Torgersen,N1A1,Yes,2007/11/11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie Penguin (Pygoscelis adeliae),Torgersen,N1A2,Yes,2007/11/11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie Penguin (Pygoscelis adeliae),Torgersen,N2A1,Yes,2007/11/16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie Penguin (Pygoscelis adeliae),Torgersen,N2A2,Yes,2007/11/16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie Penguin (Pygoscelis adeliae),Torgersen,N3A1,Yes,2007/11/16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Dream,N98A2,Yes,2009/11/19,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Dream,N99A1,No,2009/11/21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Dream,N99A2,No,2009/11/21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Dream,N100A1,Yes,2009/11/21,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Dream,N100A2,Yes,2009/11/21,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN

## 7 Suprimir la palabra "Penguin" del string que aparece en la column Species

In [6]:

df['Species'] = df['Species'].apply(lambda x: x.replace('Penguin', '') if type(x) == str else x)
df

,studyName,Sample Number,Species,Island,Individual ID,Clutch Completion,Date Egg,Culmen Length (mm),Culmen Depth (mm),Flipper Length (mm),Body Mass (g),Sex,Delta 15 N (o/oo),Delta 13 C (o/oo),Comments
0,PAL0708,1,Adelie (Pygoscelis adeliae),Torgersen,N1A1,Yes,2007/11/11,39.1,18.7,181.0,3750.0,MALE,NaN,NaN,Not enough blood for isotopes.
1,PAL0708,2,Adelie (Pygoscelis adeliae),Torgersen,N1A2,Yes,2007/11/11,39.5,17.4,186.0,3800.0,FEMALE,8.94956,-24.69454,NaN
2,PAL0708,3,Adelie (Pygoscelis adeliae),Torgersen,N2A1,Yes,2007/11/16,40.3,18.0,195.0,3250.0,FEMALE,8.36821,-25.33302,NaN
3,PAL0708,4,Adelie (Pygoscelis adeliae),Torgersen,N2A2,Yes,2007/11/16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Adult not sampled.
4,PAL0708,5,Adelie (Pygoscelis adeliae),Torgersen,N3A1,Yes,2007/11/16,36.7,19.3,193.0,3450.0,FEMALE,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,PAL0910,64,Chinstrap penguin (Pygoscelis antarctica),Dream,N98A2,Yes,2009/11/19,55.8,19.8,207.0,4000.0,MALE,9.70465,-24.53494,NaN
340,PAL0910,65,Chinstrap penguin (Pygoscelis antarctica),Dream,N99A1,No,2009/11/21,43.5,18.1,202.0,3400.0,FEMALE,9.37608,-24.40753,Nest never observed with full clutch.
341,PAL0910,66,Chinstrap penguin (Pygoscelis antarctica),Dream,N99A2,No,2009/11/21,49.6,18.2,193.0,3775.0,MALE,9.46180,-24.70615,Nest never observed with full clutch.
342,PAL0910,67,Chinstrap penguin (Pygoscelis antarctica),Dream,N100A1,Yes,2009/11/21,50.8,19.0,210.0,4100.0,MALE,9.98044,-24.68741,NaN
343,PAL0910,68,Chinstrap penguin (Pygoscelis antarctica),Dream,N100A2,Yes,2009/11/21,50.2,18.7,198.0,3775.0,FEMALE,9.39305,-24.25255,NaN

In [7]:
# 🔤 Columnas en minúsculas
df.columns = df.columns.str.lower()

# 🔤 Valores en minúsculas (robusto)
for col in df.select_dtypes(include=["object", "string"]):
    df[col] = df[col].str.lower()

df

,studyname,sample number,species,island,individual id,clutch completion,date egg,culmen length (mm),culmen depth (mm),flipper length (mm),body mass (g),sex,delta 15 n (o/oo),delta 13 c (o/oo),comments
0,pal0708,1,adelie (pygoscelis adeliae),torgersen,n1a1,yes,2007/11/11,39.1,18.7,181.0,3750.0,male,NaN,NaN,not enough blood for isotopes.
1,pal0708,2,adelie (pygoscelis adeliae),torgersen,n1a2,yes,2007/11/11,39.5,17.4,186.0,3800.0,female,8.94956,-24.69454,NaN
2,pal0708,3,adelie (pygoscelis adeliae),torgersen,n2a1,yes,2007/11/16,40.3,18.0,195.0,3250.0,female,8.36821,-25.33302,NaN
3,pal0708,4,adelie (pygoscelis adeliae),torgersen,n2a2,yes,2007/11/16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,adult not sampled.
4,pal0708,5,adelie (pygoscelis adeliae),torgersen,n3a1,yes,2007/11/16,36.7,19.3,193.0,3450.0,female,8.76651,-25.32426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,pal0910,64,chinstrap penguin (pygoscelis antarctica),dream,n98a2,yes,2009/11/19,55.8,19.8,207.0,4000.0,male,9.70465,-24.53494,NaN
340,pal0910,65,chinstrap penguin (pygoscelis antarctica),dream,n99a1,no,2009/11/21,43.5,18.1,202.0,3400.0,female,9.37608,-24.40753,nest never observed with full clutch.
341,pal0910,66,chinstrap penguin (pygoscelis antarctica),dream,n99a2,no,2009/11/21,49.6,18.2,193.0,3775.0,male,9.46180,-24.70615,nest never observed with full clutch.
342,pal0910,67,chinstrap penguin (pygoscelis antarctica),dream,n100a1,yes,2009/11/21,50.8,19.0,210.0,4100.0,male,9.98044,-24.68741,NaN
343,pal0910,68,chinstrap penguin (pygoscelis antarctica),dream,n100a2,yes,2009/11/21,50.2,18.7,198.0,3775.0,female,9.39305,-24.25255,NaN

## Df limpio sin filas en donde haya 4 valores NaN en diferentes columns

In [8]:

df_clean = df.dropna(thresh=df.shape[1] - 3)
df_clean

,studyname,sample number,species,island,individual id,clutch completion,date egg,culmen length (mm),culmen depth (mm),flipper length (mm),body mass (g),sex,delta 15 n (o/oo),delta 13 c (o/oo),comments
0,pal0708,1,adelie (pygoscelis adeliae),torgersen,n1a1,yes,2007/11/11,39.1,18.7,181.0,3750.0,male,NaN,NaN,not enough blood for isotopes.
1,pal0708,2,adelie (pygoscelis adeliae),torgersen,n1a2,yes,2007/11/11,39.5,17.4,186.0,3800.0,female,8.94956,-24.69454,NaN
2,pal0708,3,adelie (pygoscelis adeliae),torgersen,n2a1,yes,2007/11/16,40.3,18.0,195.0,3250.0,female,8.36821,-25.33302,NaN
4,pal0708,5,adelie (pygoscelis adeliae),torgersen,n3a1,yes,2007/11/16,36.7,19.3,193.0,3450.0,female,8.76651,-25.32426,NaN
5,pal0708,6,adelie (pygoscelis adeliae),torgersen,n3a2,yes,2007/11/16,39.3,20.6,190.0,3650.0,male,8.66496,-25.29805,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339,pal0910,64,chinstrap penguin (pygoscelis antarctica),dream,n98a2,yes,2009/11/19,55.8,19.8,207.0,4000.0,male,9.70465,-24.53494,NaN
340,pal0910,65,chinstrap penguin (pygoscelis antarctica),dream,n99a1,no,2009/11/21,43.5,18.1,202.0,3400.0,female,9.37608,-24.40753,nest never observed with full clutch.
341,pal0910,66,chinstrap penguin (pygoscelis antarctica),dream,n99a2,no,2009/11/21,49.6,18.2,193.0,3775.0,male,9.46180,-24.70615,nest never observed with full clutch.
342,pal0910,67,chinstrap penguin (pygoscelis antarctica),dream,n100a1,yes,2009/11/21,50.8,19.0,210.0,4100.0,male,9.98044,-24.68741,NaN
343,pal0910,68,chinstrap penguin (pygoscelis antarctica),dream,n100a2,yes,2009/11/21,50.2,18.7,198.0,3775.0,female,9.39305,-24.25255,NaN

## Eliminar columnas que no aportan datos relevantes al estudio

In [10]:

df_clean = df_clean.drop(columns=['delta 15 n (o/oo)', 'delta 13 c (o/oo)', 'comments'])
df_clean

,studyname,sample number,species,island,individual id,clutch completion,date egg,culmen length (mm),culmen depth (mm),flipper length (mm),body mass (g),sex
0,pal0708,1,adelie (pygoscelis adeliae),torgersen,n1a1,yes,2007/11/11,39.1,18.7,181.0,3750.0,male
1,pal0708,2,adelie (pygoscelis adeliae),torgersen,n1a2,yes,2007/11/11,39.5,17.4,186.0,3800.0,female
2,pal0708,3,adelie (pygoscelis adeliae),torgersen,n2a1,yes,2007/11/16,40.3,18.0,195.0,3250.0,female
4,pal0708,5,adelie (pygoscelis adeliae),torgersen,n3a1,yes,2007/11/16,36.7,19.3,193.0,3450.0,female
5,pal0708,6,adelie (pygoscelis adeliae),torgersen,n3a2,yes,2007/11/16,39.3,20.6,190.0,3650.0,male
...,...,...,...,...,...,...,...,...,...,...,...,...
339,pal0910,64,chinstrap penguin (pygoscelis antarctica),dream,n98a2,yes,2009/11/19,55.8,19.8,207.0,4000.0,male
340,pal0910,65,chinstrap penguin (pygoscelis antarctica),dream,n99a1,no,2009/11/21,43.5,18.1,202.0,3400.0,female
341,pal0910,66,chinstrap penguin (pygoscelis antarctica),dream,n99a2,no,2009/11/21,49.6,18.2,193.0,3775.0,male
342,pal0910,67,chinstrap penguin (pygoscelis antarctica),dream,n100a1,yes,2009/11/21,50.8,19.0,210.0,4100.0,male
343,pal0910,68,chinstrap penguin (pygoscelis antarctica),dream,n100a2,yes,2009/11/21,50.2,18.7,198.0,3775.0,female

## 1er borrador CSV

In [11]:

df_clean.to_csv('df_clean_penguins.csv', index=False)

## Nuevo conteo de número de individuos, especies y distribucion en las islas con el Df limpio

In [13]:
# Contar cuantas especies se han detectado
conteo_de_espeies = df_clean.groupby('species').size().reset_index(name='Count')
print("Las especies detectadas son: ")
print(conteo_de_espeies, "\n")
df


# Contar cuantas especies se han detectado por isla
avistamientos_por_isla = df_clean.groupby(['species', 'island']).size().reset_index(name='Count')
print("Los avistamientos de especies por isla son: ")
print(avistamientos_por_isla, "\n")

df_clean['island'].value_counts()

# Contar en cuántas islas aparece cada individuo
islands_por_individuo = df_clean.groupby('individual id')['island'].nunique()

# Filtrar los que aparecen en más de una isla
duplicados = islands_por_individuo[islands_por_individuo > 1]

if not duplicados.empty:
    print("individual ids presentes en múltiples islas:")
else:
    print("No hay Individual IDs en más de una isla.")

detalle = df_clean.groupby('individual id')['island'].unique()

duplicados_detalle = detalle[detalle.apply(len) > 1]

print(duplicados_detalle)

Las especies detectadas son:
                                     species  Count
0               adelie  (pygoscelis adeliae)    151
1  chinstrap penguin (pygoscelis antarctica)     68
2          gentoo penguin (pygoscelis papua)    123

Los avistamientos de especies por isla son:
                                     species     island  Count
0               adelie  (pygoscelis adeliae)     biscoe     44
1               adelie  (pygoscelis adeliae)      dream     56
2               adelie  (pygoscelis adeliae)  torgersen     51
3  chinstrap penguin (pygoscelis antarctica)      dream     68
4          gentoo penguin (pygoscelis papua)     biscoe    123

individual ids presentes en múltiples islas:
individual id
n1a1     [torgersen, biscoe]
n1a2     [torgersen, biscoe]
n21a1        [dream, biscoe]
n21a2        [dream, biscoe]
n22a1        [dream, biscoe]
                ...
n73a2     [torgersen, dream]
n7a1     [torgersen, biscoe]
n7a2     [torgersen, biscoe]
n8a1     [torgersen, biscoe]
n8a2     [torgersen, biscoe]
Name: island, Length: 77, dtype: object

##